// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/zalando/rds-health/internal/cluster (interfaces: Provider)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	rds "github.com/aws/aws-sdk-go-v2/service/rds"
	gomock "go.uber.org/mock/gomock"
)

// Cluster is a mock of Provider interface.
type Cluster struct {
	ctrl     *gomock.Controller
	recorder *ClusterMockRecorder
}

// ClusterMockRecorder is the mock recorder for Cluster.
type ClusterMockRecorder struct {
	mock *Cluster
}

// NewCluster creates a new mock instance.
func NewCluster(ctrl *gomock.Controller) *Cluster {
	mock := &Cluster{ctrl: ctrl}
	mock.recorder = &ClusterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Cluster) EXPECT() *ClusterMockRecorder {
	return m.recorder
}

// DescribeDBClusters mocks base method.
func (m *Cluster) DescribeDBClusters(arg0 context.Context, arg1 *rds.DescribeDBClustersInput, arg2 ...func(*rds.Options)) (*rds.DescribeDBClustersOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DescribeDBClusters", varargs...)
	ret0, _ := ret[0].(*rds.DescribeDBClustersOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeDBClusters indicates an expected call of DescribeDBClusters.
func (mr *ClusterMockRecorder) DescribeDBClusters(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeDBClusters", reflect.TypeOf((*Cluster)(nil).DescribeDBClusters), varargs...)
}
