project_name: rds-health

release:
  github:
    owner: zalando
    name: rds-health

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - format: binary

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - repository:
      owner: zalando
      name: rds-health
    folder: Formula
    goarm: "7"
    homepage:  https://github.com/zalando/rds-health
    description: rds-health discovers anomalies, performance issues and optimization within AWS RDS.
    license: MIT
    test: |
      system "#{bin}/rds-health -v"
