approvals:
  groups:
    zalando:
      minimum: 2
      from:
        orgs:
          - zalando

    maintainers:
      minimum: 2
      from:
        users:
          - fogfish
          - pioneerit
          - larry-dalmeida
          - tcondeixa
          - remychantenay

# mandatory pull request labels
pull-request:
  labels:
    additional: true
    oneOf:
      - architectural
      - major
      - minor
      - bugfix
      - documentation
      - dependencies

# one of [code, doc, config, tools, secrets]
X-Zalando-Type: code
X-Zalando-Team: "wardrobefi"
