##
## Unit Tests & Coverage
##
name: test
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:

  unit:
    runs-on: ubuntu-latest
    steps:

      ## actions/setup-go@v5
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491
        with:
          go-version: "1.21"

      ## actions/checkout@v4.1.1
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
     
      - name: go build
        run: |
          go build ./...
    
      - name: go test
        run: |
          go test -v $(go list ./... | grep -v /examples/)
